language: node_js #设置语言

node_js: "12.12.0" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

addons:
  ssh_known_hosts:
    - '$HOST_IP' #受信主机，你的Linux服务器ip
before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
# S: Build Lifecycle
install:
  - npm install

script:
  - npm run build:prod

#after_script前5句是把部署分支的.git文件夹保护起来，用于保留历史部署的commit日志，否则部署分支永远只有一条commit记录。
#命令里面的变量都是在Travis CI里配置过的。
after_success:
  - echo "$DOCKER_USERNAME"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t hospitalfrontend .
  - docker images
  - docker tag hospitalfrontend orozot/his:latest
  - docker push $DOCKER_USERNAME/his:latest

# E: Build LifeCycle
after_script:
  - chmod 600 ~/.ssh/id_rsa   #还是Linux文件权限问题
  - ssh travis@$HOST_IP -o StrictHostKeyChecking=no < './build/deploy.sh'   #使用ssh连接服务器

branches:
  only:
    - master
